name: Auto-generate PR Documentation

on:
  pull_request:
    types: [closed]  # Trigger when PR is closed (merged)

permissions:
  contents: write
  issues: write
  actions: write

jobs:
  create-documentation-request:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Create Documentation Request Issue
        id: create-issue
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Generate documentation for PR #${{ github.event.pull_request.number }}`,
              body: `
            @claude **URGENT DOCUMENTATION TASK**: Create documentation for merged PR #${{ github.event.pull_request.number }}

            **STEP-BY-STEP INSTRUCTIONS:**
            1. **FIRST**: Get PR #${{ github.event.pull_request.number }} diff and analyze the changes
            2. **SECOND**: Create file \`docs/prs/pr-${{ github.event.pull_request.number }}-[clean-title].md\` (clean title = lowercase, replace spaces/special chars with dashes)
            3. **THIRD**: Write comprehensive documentation using the template below
            4. **FOURTH**: Create a new PR with the documentation file

            **PR TO DOCUMENT:**
            - Title: ${{ github.event.pull_request.title }}
            - Author: ${{ github.event.pull_request.user.login }}
            - Merged: ${{ github.event.pull_request.merged_at }}
            - URL: ${{ github.event.pull_request.html_url }}

            **DOCUMENTATION TEMPLATE TO USE:**
            \`\`\`markdown
            # PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}

            ## PR Summary
            [Brief overview of what this PR accomplishes]

            ## Changes Overview
            [List of files modified and key functionality added/changed]

            ## Technical Details
            [Implementation approach, architecture decisions, key code changes]

            ## Testing
            [Tests added, modified, or testing approach used]

            ## Impact Analysis
            [Breaking changes, performance implications, compatibility notes]

            ## Future Considerations
            [Follow-up work, potential improvements, known limitations]
            \`\`\`

            **CRITICAL**: Focus on creating the documentation file immediately. Analyze the PR, write the documentation, create the file, and submit a PR. Do not spend time on extensive exploration.
            `,
              labels: ['documentation', 'auto-generated']
            });
            
            console.log(`Created issue #${issue.data.number}`);
            return issue.data.number;

      - name: Log Issue Creation
        run: |
          echo "Documentation request issue created successfully"
          echo "Claude will be automatically triggered by the @claude mention in the issue"
          echo "Issue number: ${{ steps.create-issue.outputs.result }}"
